In [5]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
  
P = int(input("Enter the number of rows:"))
Q = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m2 = np.array(entries).reshape(P, Q)
print(m2)
print("Dot Product")
d=np.dot(m1,m2)
print(d)


Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
9 8 7 6
[[9 8]
 [7 6]]
Dot Product
[[23 20]
 [55 48]]


In [6]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
transpose=m1.transpose()
print(transpose)


Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 23 5 6
[[ 1 23]
 [ 5  6]]
[[ 1  5]
 [23  6]]


In [7]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
trace=m1.trace()
print(trace)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 25 65 89
[[ 1 25]
 [65 89]]
90


In [8]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
print("Rank of the matrix:",np.linalg.matrix_rank(m1))

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
14 25 36 87
[[14 25]
 [36 87]]
Rank of the matrix: 2


In [10]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
print("determinant of the matrix is:")
print(np.linalg.det(m1))

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
12 23 56 89
[[12 23]
 [56 89]]
determinant of the matrix is:
-220.00000000000009


In [12]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
print("inverse of the matrix is:")
print(np.linalg.inv(m1))

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
12 78 56 54
[[12 78]
 [56 54]]
inverse of the matrix is:
[[-0.01451613  0.02096774]
 [ 0.01505376 -0.00322581]]


In [16]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))  
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R, C)
print(m1)
print("eigen values and eigen vectors of the matrix are:")
print(np.linalg.eig(m1))

Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
12 58 31 57
[[12 58]
 [31 57]]
eigen values and eigen vectors of the matrix are:
(array([-13.5026041,  82.5026041]), array([[-0.91541622, -0.63530923],
       [ 0.40250857, -0.77225785]]))
